### ISSUE TITLE
User Story: Filter Exercises

### ISSUE THREAD

**Issue by LorenzCoachK** [Serco627/workout-app#8]
# Filter Exercises

## Value Proposition

**As a user**

**I want to** filter exercises by muscle group,

**so that** I can quickly find exercises that target specific muscles and match my workout needs.

## Description

Capstone Group Todo: Add wireframes

## Acceptance Criteria

- The exercises list includes a section with filter options.
- Users can filter exercises by muscle groups.
- Applied filters are clearly displayed on the exercises list, allowing users to see which filters are currently active.
- Users can clear all filters with a single click, returning the list to its unfiltered state.
- The exercises list updates in real-time as filters are applied or removed.
- The filter interface is intuitive and easy to use, ensuring that new users can easily understand how to apply and clear filters.
- If no exercises match the selected filter criteria, a message is displayed indicating that no exercises were found.

## Tasks

- Create feature branch feature/filter-exercises
- Create filter section with different muscle-groups as options. 
- Once filter is applied, a filter-tag as well as a "Reset filters" field is being displayed.
- A function is implemented that filters exercises by muscle groups. 
- A filter state is being introduced that accepts the different muscle groups.
- All filters are cleared by clicking on "Reset filters".
- If no exercises match the selected filter criteria, a message is displayed indicating that no exercises were found.

**Comment by eneben** [comment]
Hello team,

overall, I like the user story. The value proposition and the acceptance criteria are clearly formulated. 👍 

In the tasks, you partly repeat what you already said in the acceptance criteria. Remember that it's more about answering possible questions from a developer, taking possible decisions away from him*her, etc. I would always put the branch name (or names of components, etc.) in backticks. Overall, the tasks are still okay, I think, and I would give you a green tick, but the wireframe is completely missing. Did you perhaps just forget to include it? You would have to add that again.

All in all, I like your app, keep it up! 😊
